# **Numpy(Numerical Python)**


*   수학 및 과학적 연산을 쉽고 빠르게 지원
*   다차원 행렬(Array/Matrix)을 효과적으로 처리
* 일반적으로 같은 데이터 타입 값으로 구성
* https://numpy.org


In [ ]:
import warnings
warnings.filterwarnings('ignore')

# I. NumPy Package import ~ as

In [ ]:
import numpy as np

* Version Check

In [ ]:
np.__version__

'1.22.4'

# II. Array 생성

*   Python List 구조를 사용




`

> # **1) Scalar - 0D Array - Rank0 Tensor**





In [ ]:
a0 = np.array(9)

In [ ]:
print(a0)

9




> # **2) Vector - 1D Array - Rank1 Tensor**



In [ ]:
a1 = np.array([1,3,5,7,9])

In [ ]:
print(a1)

[1 3 5 7 9]


In [ ]:
a1[2]

5

In [ ]:
a1[1:3]

array([3, 5])



> # **3) Matrix - 2D Array - Rank2 Tensor**



In [ ]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


* a2[행]

In [ ]:
a2[1]

array([4, 5, 6])

* a2[행,열]

In [ ]:
a2[1,1]

5

* a2[행,열]

In [ ]:
a2[:,1]

array([2, 5, 8])



> # **4) Array - 3D Array - Rank3 Tensor**



In [ ]:
a3 = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]],[[9, 10],[11, 12]]])

In [ ]:
print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


* a3[축]

In [ ]:
a3[1]

array([[5, 6],
       [7, 8]])

* a3[축,행]

In [ ]:
a3[1,1]

array([7, 8])

* a3[축,행,열]

In [ ]:
a3[1,1,1]

8

* a3[축,행,열]

In [ ]:
a3[:,0,0]

array([1, 5, 9])

* a3[축,행,열]

In [ ]:
a3[:,:,0]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

# III. AR.shape and AR.reshape( )

In [ ]:
AR = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [ ]:
print(AR)

[ 1  2  3  4  5  6  7  8  9 10 11 12]




> # 1) .shape



* 행렬 크기

In [ ]:
AR.shape

(12,)

* 행렬 차원

In [ ]:
AR.ndim

1

* 행렬 원소 개수

In [ ]:
AR.size

12



> # 2) .reshape(3, 4)



* .reshape(행, 열)

In [ ]:
AR2 = AR.reshape(3,4)

In [ ]:
print(AR2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


* 행렬 크기기

In [ ]:
AR2.shape

(3, 4)

* 행렬 차원

In [ ]:
AR2.ndim

2

* 행렬 원소 개수

In [ ]:
AR2.size

12



> # 3) .reshape(3, 2, 2)



* .reshape(축, 행, 열)

In [ ]:
AR3 = AR.reshape(3, 2, 2)

In [ ]:
print(AR3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


* 행렬의 크기

In [ ]:
AR3.shape

(3, 2, 2)

* 행렬의 차원

In [ ]:
AR3.size

12



> # 4) .reshape(-1, 1)



* .reshape(12, 1)

In [ ]:
AR.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

* .reshape(1, 12)

In [ ]:
AR2.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
AR2.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
AR3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

* .flatten( )

In [ ]:
AR3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# IV. 범위 지정(arange) 함수






> # 1) 연속된 10개 값 생성

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



> # 2) 1부터 9까지 1간격으로 생성



In [ ]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

> # 3) 1부터 9까지 2간격으로 생성

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

> # 4) Array 생성 후 .reshape( ) 적용

In [ ]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# V. 특별한 형태의 Array 생성








> # 1) 0과 1로만 구성된 Array


*  0으로만 구성

In [ ]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

* 1로만 구성

In [ ]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones([4, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* 산술연산을 적용하여 '9'로만 구성된 행렬 생성

In [ ]:
np.zeros([3, 4]) + 9

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

> # 2) 3 x 3 단위행렬

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

> # 3) 난수 Array 생성

* 실수 난수 생성
  * (축, 행, 열)


In [ ]:
np.random.rand(3, 2, 2)

array([[[0.76043748, 0.48591448],
        [0.6514954 , 0.76588605]],

       [[0.5299852 , 0.53486729],
        [0.98155563, 0.11446526]],

       [[0.85609244, 0.97203901],
        [0.79657618, 0.20285579]]])

* 주어진 정수 범위에서 난수 생성
  * 1 ~ 44 사이
  * 복원 추출
  * (행, 열)



In [ ]:
np.random.randint(1, 45, size = (5, 6))

array([[ 8, 25,  6,  3, 19, 38],
       [38, 42, 39, 43, 11, 31],
       [27, 35,  9, 24, 20, 23],
       [ 6, 18, 44, 24, 12,  6],
       [18, 16, 28, 20, 12, 20]])

* np.random.seed( )
  * 의사난수(Pseudo Random Number) 생성 초기값 지정
  * 항상 같은 난수 생성
  * 비복원 추출

In [ ]:
np.random.seed(2045)
np.random.choice(np.arange(1, 46), size = (5 ,6), replace = False)

array([[ 7, 32,  6, 41,  4, 34],
       [30, 28, 16,  5, 38, 33],
       [31, 13, 25, 23, 43, 12],
       [45,  8, 29, 22, 18,  9],
       [21, 20, 40,  2, 37, 39]])

* shuffle( )
  * 원소 섞기

In [ ]:
TA = np.arange(1, 10)
TA

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(TA)
TA

array([7, 6, 5, 4, 3, 1, 8, 2, 9])

# VI. Array 연산

In [ ]:
A1 = np.array([85, 93, 75, 97, 69])
A2 = np.array([91, 90, 85, 97, 89])
A3 = np.array([[85, 93, 75],[90, 84, 97],[99, 91, 80]])

> # 1) 기본 연산
* 각각의 행과 열의 값을 매칭하여 연산 수행

In [ ]:
A1 + A2

array([176, 183, 160, 194, 158])

In [ ]:
A2 - A1

array([ 6, -3, 10,  0, 20])

In [ ]:
A1 * A2

array([7735, 8370, 6375, 9409, 6141])

In [ ]:
A2 / A1

array([1.07058824, 0.96774194, 1.13333333, 1.        , 1.28985507])

In [ ]:
A1 * 3

array([255, 279, 225, 291, 207])

In [ ]:
A1 ** 2

array([7225, 8649, 5625, 9409, 4761])

> # 2) 통계량 연산

* 총합

In [ ]:
A1.sum()

419

* 평균

In [ ]:
A2.mean()

90.4

* 분산
  * 'ddof = 0'

In [ ]:
A2.var()

15.040000000000001

* 표준 편차
  * 'ddof = 0'

In [ ]:
A2.std()

3.8781438859330635

* 최소값

In [ ]:
A2.min()

85

> * A3 전체 최소값

In [ ]:
A3.min()

75

> * A3 각 열의 최소값

In [ ]:
A3.min(axis = 0)

array([85, 84, 75])

> * A3 각 행의 최소값

In [ ]:
A3.min(axis = 1)

array([75, 84, 80])

In [ ]:
A3.min(axis = 1, keepdims = True)

array([[75],
       [84],
       [80]])

* 최대값

In [ ]:
A2.max()

97

> * A3 전체 최대값

In [ ]:
A3.max()

99

> * A3 각 열의 최대값

In [ ]:
A3.max(axis = 0)

array([99, 93, 97])

> * A3 각 행의 최대값

In [ ]:
A3.max(axis = 1)

array([93, 97, 99])

In [ ]:
A3.max(axis = 1, keepdims = True)

array([[93],
       [97],
       [99]])

* 누적(Cumulative)합

In [ ]:
A1.cumsum()

array([ 85, 178, 253, 350, 419])

* 누적(Cumulative)곱

In [ ]:
A1.cumprod()

array([        85,       7905,     592875,   57508875, 3968112375])

# VII. Matrix 연산

* M1, M2 지정

In [ ]:
M1 = np.array([2, 4, 6, 8]).reshape(2, 2)

In [ ]:
print(M1)

[[2 4]
 [6 8]]


In [ ]:
M2 = np.array([3, 5, 7, 9]).reshape(2, 2)

In [ ]:
print(M2)

[[3 5]
 [7 9]]


> # 1) Matrix 곱
* M1 @ M2

In [ ]:
M1.dot(M2)

array([[ 34,  46],
       [ 74, 102]])

* M2 @ M1

In [ ]:
np.dot(M2, M1)

array([[ 36,  52],
       [ 68, 100]])

* Warning: M1 * M2

In [ ]:
M1 * M2

array([[ 6, 20],
       [42, 72]])

In [ ]:
M2 * M1

array([[ 6, 20],
       [42, 72]])


> # 2) 전치 행렬

* M1의 전치 행렬

In [ ]:
np.transpose(M1)

array([[2, 6],
       [4, 8]])

* M2의 전치 행렬

In [ ]:
M2.transpose()

array([[3, 7],
       [5, 9]])

In [ ]:
M2.T

array([[3, 7],
       [5, 9]])